

create table mydata_config(
title         varchar(200),
description   varchar(300),
keywords      varchar(200),
beian         varchar(100),
bottom        varchar(300),
is_closed     tinyint(1) default 0
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci;

create table mydata_user(
USER_ID       INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
USERNAME      VARCHAR(20)  NOT NULL,
USERPASSWORD  VARCHAR(40)  NOT NULL,
EMAIL_ADDR    VARCHAR(100),
IS_SUPER      TINYINT(1)   DEFAULT 0,
IS_ACTIVE     TINYINT(1)   DEFAULT 1,
PRIMARY KEY(USER_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table mydata_news(
NEWS_ID      BIGINT(20) UNSIGNED NOT NULL  AUTO_INCREMENT,
CATEGORY_ID  BIGINT(20) UNSIGNED,   
TITLE        VARCHAR(200) NOT NULL,
KEYWORDS     VARCHAR(200) NOT NULL,
AUTHER       VARCHAR(100),
CONTENT      TEXT,
IS_TOP       TINYINT(1)   DEFAULT 0,
NEWS_TIME    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(NEWS_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table  mydata_category(
CATEGORY_ID  INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
PARENT_ID    INTEGER UNSIGNED NOT NULL  DEFAULT 0,
NAME         VARCHAR(100) NOT NULL,
DESCRIPTION  VARCHAR(200) NOT NULL,
PRIMARY KEY(CATEGORY_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table mydata_product(
PRODUCT_ID   BIGINT(20)   UNSIGNED NOT NULL  AUTO_INCREMENT,
CATEGORY_ID  BIGINT(5),
NAME         VARCHAR(200) NOT NULL,
NUMBER       VARCHAR(100),
SPECIFICATION VARCHAR(200),
INTRODUCTION TEXT,
PRODUCTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(PRODUCT_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table mydata_guestbook(
MSG_ID       BIGINT(20)   UNSIGNED NOT NULL  AUTO_INCREMENT,
MSG_CONTACT  VARCHAR(50)  NOT NULL,
COMPANY      VARCHAR(100) ,
TEL          VARCHAR(20)  ,
FAX          VARCHAR(20),
EMAIL        VARCHAR(100) ,
TITLE        VARCHAR(200) ,
CONTENT      VARCHAR(1000),
MSG_TIME     TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(MSG_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table mydata_link(
LINK_ID     INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
LINK_NAME   VARCHAR(100),
LINK_DESCRIPTION  VARCHAR(500),
LINK_IMG    VARCHAR(200),
LINK_URL    VARCHAR(200),
LINK_TIME   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(LINK_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table mydata_job(
JOB_ID    INTEGER UNSIGNED NOT NULL  AUTO_INCREMENT,
JOB_POISTION  VARCHAR(50),
EDUCATION     VARCHAR(30),
ZHUANYE       VARCHAR(100),
XINGZHI       VARCHAR(30),
NUMBER        VARCHAR(10),
AGE           VARCHAR(10),
SEX           VARCHAR(10),
DESCRIPTION   VARCHAR(1000),
JOB_TIME      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(JOB_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER
 SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table mydata_company(
ID      BIGINT(20) UNSIGNED NOT NULL  AUTO_INCREMENT,
CATEGORY_ID  BIGINT(20) UNSIGNED,    
CONTENT      TEXT,
NEWS_TIME    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

create table mydata_log(
ID      BIGINT(20) UNSIGNED NOT NULL  AUTO_INCREMENT,   
USERNAME     VARCHAR(20),
CONTENT      VARCHAR(200),
LOGTIME    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci AUTO_INCREMENT=1;

INSERT INTO mydata_CATEGORY (CATEGORY_ID,PARENT_ID,NAME,DESCRIPTION) VALUES
(1, 0, '关于我们', '关于我们'),
(2, 0, '产品展示', '产品展示'),
(3, 0, '新闻中心', '新闻中心'),
(4, 0, '联系我们', '联系我们'),
(5, 1, '公司概况', '公司概况'),
(6, 1, '资质荣誉', '资质荣誉'),
(7, 1, '销售网络', '销售网络'),
(8, 1, '公司位置', '公司位置');

INSERT INTO mydata_COMPANY (ID, CATEGORY_ID,CONTENT) VALUES
(1, 5, '公司概况'),
(2, 6, '资质荣誉'),
(3, 7, '销售网络'),
(4, 8, '公司位置'),
(5, 4, '联系我们');

INSERT INTO mydata_USER (USER_ID,USERNAME,USERPASSWORD,EMAIL_ADDR, IS_SUPER,IS_ACTIVE) VALUES (NULL, 'yovae', 'yovae', NULL, '1', '1');





     

       











